# Generated by Django 4.2.4 on 2023-09-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_icon', models.IntegerField()),
                ('sum_level', models.IntegerField()),
                ('first_champ', models.CharField(max_length=200)),
                ('second_champ', models.CharField(max_length=200)),
                ('thr_champ', models.CharField(max_length=200)),
            ],
        ),
    ]
